/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEpochHumanReadableTime.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   epoch/v1
// Description:
//   Epoch API v1.
// Classes:
//   GTLEpochHumanReadableTime (0 custom class methods, 1 custom properties)

#import "GTLEpochHumanReadableTime.h"

// ----------------------------------------------------------------------------
//
//   GTLEpochHumanReadableTime
//

@implementation GTLEpochHumanReadableTime
@dynamic message;
@end
