/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEpoch.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   epoch/v1
// Description:
//   Epoch API v1.

#import "GTLEpochConstants.h"

#import "GTLEpochHumanReadableTime.h"

#import "GTLQueryEpoch.h"
#import "GTLServiceEpoch.h"
