/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryEpoch.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   epoch/v1
// Description:
//   Epoch API v1.
// Classes:
//   GTLQueryEpoch (1 custom class methods, 2 custom properties)

#import "GTLQueryEpoch.h"

#import "GTLEpochHumanReadableTime.h"

@implementation GTLQueryEpoch

@dynamic fields, sec;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryEpoch object.

+ (id)queryForGetEpochWithSec:(long long)sec {
  NSString *methodName = @"epoch.getEpoch";
  GTLQueryEpoch *query = [self queryWithMethodName:methodName];
  query.sec = sec;
  query.expectedObjectClass = [GTLEpochHumanReadableTime class];
  return query;
}

@end
