/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryEpoch.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   epoch/v1
// Description:
//   Epoch API v1.
// Classes:
//   GTLQueryEpoch (1 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryEpoch : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) long long sec;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryEpoch object.

// Method: epoch.getEpoch
//  Authorization scope(s):
//   kGTLAuthScopeEpochUserinfoEmail
// Fetches a GTLEpochHumanReadableTime.
+ (id)queryForGetEpochWithSec:(long long)sec;

@end
